Likelion-13th-EGSBI/Likelion-13th-EGSBI-FE

front/src/App.js, front/src/css/mypage.css, front/src/pages/MyPage.jsx
- 마이페이지 초기 디자인 완료, 반응형
- 초기 디자인 수정(사이드바 제거)
- 버튼위치 변경
- 모바일 환경 디자인 변경
- Closed 이슈: #4
=> design: 마이페이지 작업 완료(#4)

front/package-lock.json, front/package.json, front/src/App.js, front/src/components/Layout.jsx, front/src/components/Sidebar.jsx, front/src/components/TopBar.jsx, front/src/css/eventupload.css, front/src/css/layout.css, front/src/css/sidebar.css, front/src/css/topbar.css, front/src/pages/EventUpload.jsx
- 행사 등록페이지 ui구현 완료
- 사이드바 구현
- 상단바 구현(pc,모바일 다르게 보이게 구현, 모바일 버전 헤더는 메인페이지 이외 경로는 뒤로가기 버튼과 페이지 제목이 오도록 구현)
- Closes: #11
=> design: 행사 등록 페이지 및 사이드바, 상단바 구현 완료

front/src/css/mypage.css, front/src/pages/MyPage.jsx
- 마이페이지 상단바, 하단바 영역 리팩토링
- css layout 수정
- Closes: #4 
-전체 화면
- 반쪽 화면
- 모바일 환경
=> refactor: 마이페이지 구조변경

front/src/components/HostCard.jsx, front/src/css/hostcard.css, front/src/css/subscribe.css, front/src/pages/HostDetail.jsx, front/src/pages/SubscribePage.jsx
- 구독 주최자 목록 무한 스크롤 적용
- 반응형 UI 적용 (데스크탑 / 모바일 대응)
- API 연동 구조 추가 및 로딩/에러 처리
- 공통 HostCard 컴포넌트 생성 및 스타일링
- Closes: #25 
- Related to: #37 
- 반응형 CSS 구조나 카드 UI 구조가 적절한지 검토 부탁드립니다.
- API 연동 부분에서 페이지네이션 처리 방식 피드백 요청드립니다.
=> feat: 구독 페이지 구현 (SubscribePage)

front/src/components/EventCard.jsx, front/src/css/eventcard.css, front/src/css/hostcard.css, front/src/css/hostdetail.css, front/src/pages/HostDetail.jsx
=> feat: HostDetail, EventCard UI 업데이트

front/src/App.js
=> fix: app.js 중복 선언 제거

front/src/App.js, front/src/css/myuploadevent.css, front/src/pages/MyPage.jsx, front/src/pages/MyUploadEvent.jsx
- 내가 등록한 행사 ui개발 및 API 연결
- 업로드 순으로 카드 정렬
- app.js 라우팅 추가
- 마이페이지 네비게이션 추가
- 행사 마감일 기준으로 수정하기/리뷰보기 버튼 추가
- Closes: #13 
- Related to: #14
=> feat: 내가 등록한 행사 UI개발 및 API 연결

front/src/App.js, front/src/components/TopBar.jsx, front/src/css/bookmark-joined.css, front/src/pages/BookmarkedEvents.jsx, front/src/pages/JoinedEvents.jsx
- 북마크 화면에 List/Map 토글(pill 버튼) 추가
- 반응형 카드 그리드 적용(PC 3열 · 태블릿 2열 · 모바일 1열)
- 정렬 최신순/거리순 지원, 변경 시 자동 재요청
- 마감 포함 토글 추가(온/오프마다 즉시 재요청)
- 북마크한 행사만 필터링 표시
- 카드 클릭 시 /events/:id로 상세 이동
- 카카오 지도 연동 + SDK 동적 로딩/중복 방지
- 프로젝트 메인 컬러 기반 커스텀 SVG 마커 적용
- 마커 클릭 시 커스텀 오버레이(제목·위치·일시·요금·상세보기)
- 오버레이 상단 배치 + 화살표 스타일, 터치 제스처 충돌 방지
- 지도 전체폭 하단 배치, 드래그/확대·축소 활성화
- 지도 진입 시 위치 권한 1회 요청(Permissions API), 거리순 전환 시 자동 요청
- “내 위치” 버튼 클릭 시 즉시 센터/줌, dot+pulse 마커(yAnchor 보정)
- 안정성 개선: 세션 가드/클린업, 이벤트 버블링 차단, 키보드 접근성 보강
- 스타일 정리: 공통 색/그림자/반경 등 UI 톤 통일
- Related to: #19 
- 지도 SDK 키 관리: 현재 예시로 스크립트에 appkey 하드코딩되어 있음. 머지 전 .env로 분리(REACT_APP_KAKAO_MAP_KEY) 후 sdk.js?appkey=${...} 형태로 교체 예정인데, 레포 환경 변수 전략 합의 부탁드립니다.
- 데이터 연동: 현재는 DUMMY 데이터 기준으로 정렬/마커 표시. 백엔드 연동 시 필드명(lat/lng/date/time/fee) 매핑 컨벤션 검토 부탁드립니다.
- 접근성: 오버레이 …
=> feat: 북마크 페이지 카드형 UI + 카카오 지도 연동 구현 (#19)

front/src/App.js, front/src/components/Sidebar.jsx, front/src/css/initmain.css, front/src/pages/InitMain.jsx
=> design: 임시 메인페이지 작업

front/src/css/initmain.css
=> test: cicd 테스트

.github/workflows/deploy.yml
=> fix: depoly.yml 수정

front/src/css/initmain.css
=> test:cicd 테스트

front/src/css/bookmark-joined.css
- 지도 infowindow UI 수정
- Closed to: #13
=> refactor: 지도 infowindow 수정

front/src/css/bookmarkedevents.css, front/src/css/joinedevents.css, front/src/css/review-modal.css, front/src/pages/BookmarkedEvents.jsx, front/src/pages/JoinedEvents.jsx
- bookmark-joined.css -> joinedevents.css 와 bookmarkedevents.css로 분리
- 내가 참여한 행사 페이지 리뷰버튼 및 이벤트카드 구조 수정
- 내가 참여한 행사 페이지 반응형 UI 개선 및 디자인 수정
- Related to: #21
=> refactor: 내가 참여한행사

front/src/App.js, front/src/css/mainpage.css, front/src/pages/MainPage.jsx
- 사용자 카드
- AI 추천 행사
- 우리동네 인기 행사
- 가로 스크롤
=> [feat] MainPage UI 작업

front/src/App.js, front/src/css/checkinpage.css, front/src/css/eventupload.css, front/src/pages/CheckInPage.jsx, front/src/pages/EventUpload.jsx, front/src/pages/LoginPage.jsx
- 행사 등록 페이지 참가자 삭제
- 행사 등록 페이지 마크다운 지원 추가
- 행사 등록 완료시 QR 생성
- QR 체크인 페이지 ui 작업 완
- Closes: #76, #83
- Reated to: #12
=> refactor: 행사 업로드 API 연결 수정 및 QR 체크인 연결완료(#76,#83)

front/src/pages/CheckInPage.jsx
=> feat: 체크인 API 연결(#84)

front/src/css/mypage.css, front/src/pages/MyPage.jsx
- 마이페이지 상단 프로필카드 프로필 수정 적용부분 api 수정
- Closes: #5
=> refactor: 프로필카드 부분 api 수정

front/src/css/editprofile.css, front/src/pages/EditProfile.jsx
- 프로필 수정 api 연결 완료
- Closes: #7
=> editprofile api 연결완료

front/src/pages/EditProfile.jsx, front/src/pages/MyPage.jsx
- 마이페이지 이미지 로딩 안되는 부분 수정
- 프로필 수정 페이지 새로고침시 이미지 날아가는 부분 백엔드에 전달 및 수정 완료
- Closes: #7
=> refactor: 프로필 수정 + 마이페이지 api 수정

front/src/css/myuploadevent.css, front/src/pages/MyUploadEvent.jsx
- 내가 등록한 행사 리뷰 보기 API 및 UI 연결
- Closes: #96
=> feat: 내가 등록한 행사 리뷰 보기 API 연결(#96)

front/src/components/EventCard.jsx
- 이벤트카드 행사정보 마크다운 적용
- Closes: #55
- Related to: #55
=> refactor: EventCard markdown 적용

front/src/App.js, front/src/css/emailverification.css, front/src/css/signuppage.css, front/src/pages/EmailVerificationPage.jsx, front/src/pages/SignupPage.jsx
- 회원가입 후 이메일인증 페이지로 이동
- Closes: #102
=> feat: 이메일 인증 페이지 추가(#102)

front/src/css/joinedevents.css, front/src/pages/JoinedEvents.jsx
- 리뷰없을때 빈 페이지 ui 수정
- Closes: #21
=> refactor: 내가 참여한 행사 ui수정

front/src/pages/EventAll.jsx
- 전체 행사 페이지 페이징 처리 개수 40 -> 20 변경
=> refactor: 전체 행사 페이지 페이징 처리 개수 20으로 변경

front/src/css/mypage.css, front/src/pages/MyPage.jsx
- mypage 전반적인 ui 수정
- Closes: #4
=> refactor: mypage UI 수정

front/src/css/myuploadevent.css, front/src/pages/MyUploadEvent.jsx
- 내가 등록한 행사 QR 보기 추가
- Related to: #13
=> refactor: 내가 등록한 행사 QR 보기 추가

front/src/css/bookmarkedevents.css, front/src/pages/BookmarkedEvents.jsx
- 북마크 페이지 상단 헤더 추가
- Closes: #19
=> refactor: bookmarkedevents 상단 헤더 추가

front/src/components/HostCard.jsx, front/src/components/Sidebar.jsx
=> refactor: 사이드바 ui 수정
